# This workflow performs lint checks and builds the project.
#
# Scans are triggered:
# 1. On every push to default and protected branches
# 2. On every Pull Request targeting the default branch
# 3. Manually, on demand, via the "workflow_dispatch" event

name: Lint Checks & Build

# Triggers the workflow on push or pull request events but only for default and protected branches
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  spotless:
    name: Spotless
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 17
          distribution: 'oracle'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3.3.2
        with:
          path: ~/${{ env.WORKING_DIR }}/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Detekt
        working-directory: ${{ env.WORKING_DIR }}
        run: ./gradlew spotlessCheck

  detekt:
    name: Detekt
    needs: [ spotless ]
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 17
          distribution: 'oracle'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3.3.2
        with:
          path: ~/${{ env.WORKING_DIR }}/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Detekt
        working-directory: ${{ env.WORKING_DIR }}
        run: ./gradlew detektAll

  build:
    name: Build
    needs: [ detekt ]
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 17
          distribution: 'oracle'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3.3.2
        with:
          path: ~/${{ env.WORKING_DIR }}/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        working-directory: ${{ env.WORKING_DIR }}
        run: ./gradlew build
